name: Generate Diagrams
on:
  push:
    branches: [ main ]
concurrency: ${{ github.workflow }}
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: apt install graphviz
      - run: pip install diagrams
      - run: |
          for entry in $(find . -path "*.py")
          do
              python $entry
          done